[project]
name = "headphone-auto-switcher"
version = "3.0.0a1"
requires-python = ">=3.14"
dependencies = [
    "pywinusb==0.4.2",
    "simplifiedcli==1.2.0",
    "pywin32==312",
    "python-dateutil>=2.9.0",
    "click==8.5.0",
]

# TODO(Ryan): Make an internal library for base types


[project.optional-dependencies]
dev = [
    "pyinstaller>=6.21.0",
    "pytest-check>=2.9.1",
    "pytest-cov>=7.1.0",
    "pytest>=9.1.1",
]

[project.scripts]
cli = "infrastructure.cli:main"

[tool.pytest]
markers = [
    "unit",
    "integration",
    "end_to_end",
    "architectural",
]

[tool.coverage.report]
exclude_also = [
    "assert_never(.*)",
    'if __name__ == .__main__.:',
    'if TYPE_CHECKING:',
]

[tool.uv]
system-certs = true

[tool.ruff]
# https://docs.astral.sh/ruff/settings/
fix = true
line-length = 120

[tool.ruff.format]
# https://docs.astral.sh/ruff/settings/#format
docstring-code-format = true
docstring-code-line-length = "dynamic"

[tool.ruff.lint]
# https://docs.astral.sh/ruff/settings/#lint
select = ["ALL"]
ignore = [
    "A001",
    "A002",
    "A003",
    "A004",
    "A005",
    "A006",
    "ANN401",
    "B024",
    "B027",
    "COM812",
    "D203",
    "D213",
    "D401",
    "DTZ005",
    "EM101",
    "EM102",
    "ERA001",
    "F405",
    "FBT001",
    "FBT002",
    "FBT003",
    "FIX002",
    "INP001",
    "LOG007",
    "PLR0913",
    "PLR0915",
    "PLW0603",
    "PT028",
    "S311",
    "TD003",
    "TRY003",
]

[tool.ruff.lint.per-file-ignores]
"test/*" = [
    "INP001",
    "N999",
    "PLC0415",
    "PLR0915",
    "PLR2004",
    "S101",
    "S311",
    "S324",
    "T201",
    "TC005",
]

[tool.ruff.lint.isort]
# https://docs.astral.sh/ruff/settings/#lintisort
force-single-line = true
required-imports = ["from __future__ import annotations"]
